### ISSUE TITLE
Project import not working

### ISSUE THREAD

**Issue by asmittal** [salesforce/bazel-eclipse#154] opened 2020-07-20 16:47 UTC
I followed the guide here: https://github.com/salesforce/bazel-eclipse/blob/master/docs/using_the_feature_import.md. 

Have set build --javacopt=-source 8 -target 8 in the .bazelrc both at the user home location and also at the workspace folder location. But still on importing the workspace file I get error: 
Unbound classpath container: 'JRE System Library [JavaSE-11]' in project 'Bazel Workspace (root)' ...
What can I do ? 

Also in the bazelproject file > Under directories: section when i try to add the module that I want to build it always says "Bad Bazel Package"
Whats the format, any example.

Have downloaded the plugin version just yesterday. 
Eclipse version: 2020-06 (4.16.0)
Build id: 20200615-1200

**Comment by plaird** [comment] 2020-07-21 14:37
Sorry it is not working for you. The unbound classpath container issue is within the standard Eclipse Java Tooling, not the Bazel feature.  There are a number of articles out there that present solutions, like:
https://sites.miis.edu/dreadkingrathalos/2017/06/05/unbound-classpath-container-jre-system-library-resolved/
Can you try a few of them to see if you can fix it? 

For the 'bad bazel package' issue, the problem is at least one line in your project view file is pointing to a location that does not have a BUILD file. We borrowed this feature from the IntelliJ Bazel plugin, and they have a doc here that explains it pretty well:
https://ij.bazel.build/docs/import-project.html

Let me know if these don't help you.

**Comment by asmittal** [comment] 2020-07-23 13:17
Thanks for the response. 
Ubound issue I am able to solve by changing the library manually, my concern was that plugin is not honoring the --javacopt=-source 8 -target 8 option. Anyways, as there is work around we can ignore this issue for now. 

But the 'bad package' issue still exist. **The same entries are working fine in intelliJ** but not in eclipse. 

Say my workspace root is **/Users/Source_Root**  with my **WORKSPACE** File 

And my module structure is:  **/Users/Source_Root/A/B/Module1**

Where Module1 folder is having the **BUILD** file, then below is the entry that is giving error: 

directories:
  A/B/Module1

Any idea?

**Comment by plaird** [comment] 2020-07-23 15:34
OK, thanks for trying the manual approach with the JDK. There is some logic to try and automate this, but it seems not to be working in your case. 

https://github.com/salesforce/bazel-eclipse/blob/master/plugin-core/src/main/java/com/salesforce/bazel/eclipse/config/BazelEclipseProjectFactory.java#L412

I will break this out into a separate issue to investigate. Can you run this command on the command line in your Bazel workspace and provide the output:

```bazel test --announce_rc```


For the Project View issue, can you import the workspace without using one (just manually click the boxes in the tree). I wonder if this is something in your Bazel workspace structure rather than the Project View. It would be nice to verify that this is a project view issue. Thanks!

**Comment by asmittal** [comment] 2020-07-24 04:31
I didn't get this part, can you please rephrase. 
"For the Project View issue, can you import the workspace without using one (just manually click the boxes in the tree). "

As such the steps given in documentation don't match on my mac. The documentation says to select the folder where the WORKSPACE file is present. But I have to select the workspace file. Selecting folder keeps the "Open" button disabled. 
Also the WORKSPACE file for us is actually an alias for the actual file (actual file is bit deeper in the folder structure)

**Comment by plaird** [comment] 2020-07-24 21:24
OK, thanks for the response. I have updated our user docs for import. It now correctly mentions that you need to click on the WORKSPACE file, not just the directory that contains it. 

I also think there is confusion here about Project Views. I have also updated the documentation for that to make it clear a Project View files is optional. You only use one if you are working in a large Bazel workspace, and want to share a list of typical packages to import with your team members.

Can you review the updated documentation and let me know if it still isn't clear:
https://github.com/salesforce/bazel-eclipse/blob/master/docs/using_the_feature_import.md

Finally, if you continue to have trouble, can you temporarily copy your WORKSPACE file to the root of your Bazel workspace? We do resolve soft links but I wonder if BEF is getting confused as to what directory it should be recursively scanning for BUILD files.

Out of curiosity, what is the purpose of not having your WORKSPACE file at the root? I haven't seen that before.

**Comment by asmittal** [comment] 2020-08-19 09:19
Updated Documentation looks good now. 
After coping workspace file to to root of workspace, the import worked properly 
Though slow but I could see all the packages in the Bazel Java Packages tree view (I have a very huge package structure)
I imported my package. It showed in Eclipse, bazel build worked properly. 

Current issues: 
1) Can the soft link issue be fixed so that copy WORKSPACE file is not required. 
2) Bazel build ran fine, also I don't see any error in the Problems view, but on opening any Java file, its full of errors for any external dependencies. "<Class Cannnot be resolved> cannot be resolved to a type" . Can you help with that .

**Comment by plaird** [comment] 2020-08-19 16:27
_"the import worked properly"_
Great!

_"Though slow..."_
That is a polite way to put it 😵 . Import performance will be the focus of our next round of development. It is pretty bad. The issue is we are computing the classpath for every java_test target in every BUILD file, which is very inefficient. We do this so we can correctly identify deps as _main_ or _test_ classpath in Eclipse Java Tooling but it is too slow. Issue:  #131 

_"Can the soft link issue be fixed so that copy WORKSPACE file is not required."_
I can file an Issue for it, but I would like to know why you are doing this? Why not have the WORKSPACE file in the root of the repo?

_"Bazel build ran fine, also I don't see any error in the Problems view, but on opening any Java file, its full of errors for any external dependencies. "XXX cannot be resolved to a type" . Can you help with that ."_
Can you file a new issue for that and provide screenshots and more info. For example, are you using maven_install or jvm_import_external. Can you show the WORKSPACE entries for those, a sample BUILD file, and a screen shot of the Package Explorer with the Bazel Classpath Container expanded.

**Comment by plaird** [comment] 2020-09-08 17:08
Closing this particular issue. If you can provide more information, we can file new issues for the soft link use case, and for the dependency problem.

**Closed by plaird** 2020-09-08 17:08 UTC
